/**
 * ExamShield AI — Face Embedding Service
 *
 * The ONLY valid enrollment embedding is a real 512-D FaceNet
 * (InceptionResnetV1 / vggface2) embedding generated by embedding_server.py.
 * There is deliberately NO random/fallback embedding.
 */

const EMBED_SERVER_URL =
  import.meta.env.VITE_EMBED_SERVER_URL || 'http://localhost:5005/embed';
const EMBED_SERVER_TIMEOUT_MS = 30000;

async function fetchRealEmbedding(imageData) {
  if (!imageData) {
    throw new Error('No image was provided for face embedding.');
  }

  let body;
  const headers = {};

  if (typeof File !== 'undefined' && imageData instanceof File) {
    const formData = new FormData();
    formData.append('file', imageData, imageData.name || 'student-photo.jpg');
    body = formData;
  } else if (typeof Blob !== 'undefined' && imageData instanceof Blob) {
    const formData = new FormData();
    formData.append('file', imageData, 'student-photo.jpg');
    body = formData;
  } else if (typeof imageData === 'string' && imageData.startsWith('data:')) {
    body = JSON.stringify({ image_b64: imageData });
    headers['Content-Type'] = 'application/json';
  } else if (
    typeof imageData === 'string' &&
    (imageData.startsWith('http://') || imageData.startsWith('https://'))
  ) {
    body = JSON.stringify({ image_url: imageData });
    headers['Content-Type'] = 'application/json';
  } else {
    throw new Error('Unsupported student image format.');
  }

  const controller = new AbortController();
  const timeoutId = setTimeout(
    () => controller.abort(),
    EMBED_SERVER_TIMEOUT_MS
  );

  try {
    const response = await fetch(EMBED_SERVER_URL, {
      method: 'POST',
      headers,
      body,
      signal: controller.signal,
    });

    const result = await response.json().catch(() => ({}));

    if (!response.ok) {
      throw new Error(
        result.error ||
        `Embedding server returned HTTP ${response.status}.`
      );
    }

    if (!Array.isArray(result.embedding)) {
      throw new Error('Embedding server did not return an embedding.');
    }

    if (result.embedding.length !== 512) {
      throw new Error(
        `Invalid embedding dimension: expected 512, received ${result.embedding.length}.`
      );
    }

    if (result.face_count !== 1) {
      throw new Error(
        `Exactly one face is required. Detected ${result.face_count || 0}.`
      );
    }

    const embedding = result.embedding.map(Number);

    if (embedding.some(value => !Number.isFinite(value))) {
      throw new Error('Embedding contains invalid numeric values.');
    }

    return JSON.stringify(embedding);
  } catch (err) {
    if (err.name === 'AbortError') {
      throw new Error(
        'Face embedding server timed out. Start embedding_server.py and try again.'
      );
    }

    if (err instanceof TypeError) {
      throw new Error(
        'Cannot reach the FaceNet embedding server at http://localhost:5005. Start embedding_server.py and try again.'
      );
    }

    throw err;
  } finally {
    clearTimeout(timeoutId);
  }
}

export async function generateFaceEmbedding(imageData) {
  if (!imageData) {
    throw new Error('No image provided for face embedding.');
  }

  let resolvedImage = imageData;

  if (
    typeof imageData === 'object' &&
    !(typeof File !== 'undefined' && imageData instanceof File) &&
    !(typeof Blob !== 'undefined' && imageData instanceof Blob)
  ) {
    resolvedImage = imageData.photo;
  }

  if (!resolvedImage) {
    throw new Error('No valid student photo available.');
  }

  return fetchRealEmbedding(resolvedImage);
}

export function parseEmbedding(embeddingInput) {
  if (!embeddingInput) return null;

  if (Array.isArray(embeddingInput)) {
    const values = embeddingInput.map(Number);
    return values.length === 512 && values.every(Number.isFinite)
      ? values
      : null;
  }

  if (typeof embeddingInput === 'string') {
    try {
      const parsed = JSON.parse(embeddingInput);
      if (Array.isArray(parsed)) {
        const values = parsed.map(Number);
        return values.length === 512 && values.every(Number.isFinite)
          ? values
          : null;
      }
    } catch (e) {
      console.warn('[EmbeddingService] Failed to parse embedding:', e.message);
    }
  }

  return null;
}

export function cosineSimilarity(vecA, vecB) {
  const arrA = parseEmbedding(vecA);
  const arrB = parseEmbedding(vecB);

  if (!arrA || !arrB) return 0;

  let dotProduct = 0;
  let normA = 0;
  let normB = 0;

  for (let i = 0; i < 512; i++) {
    dotProduct += arrA[i] * arrB[i];
    normA += arrA[i] * arrA[i];
    normB += arrB[i] * arrB[i];
  }

  if (normA === 0 || normB === 0) return 0;

  return dotProduct / (Math.sqrt(normA) * Math.sqrt(normB));
}

export function formatEmbeddingPreview(embedding) {
  const arr = parseEmbedding(embedding);
  if (!arr) return 'No Valid 512D Embedding';

  return `[512D Vector: ${arr
    .slice(0, 3)
    .map(n => n.toFixed(4))
    .join(', ')}, ...]`;
}
